<h1><b> Import Modules

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.model_selection import train_test_split,TimeSeriesSplit
from sklearn.metrics import mean_absolute_error

<h1><b> Define Functions

In [2]:
def all_weeks(a):
    w_1= a.iloc[:168,:] 
    w_2=a.iloc[168:336,:]
    w_3= a.iloc[336:504,:]
    w_4=a.iloc[504:672,:]
    w_5= a.iloc[672:840,:]
    return w_1,w_2,w_3,w_4,w_5

In [3]:
def melt_(a_,b_,c_,d_,e_):
    a=a_.melt(var_name='column', value_name='value')
    b=b_.melt(var_name='column', value_name='value')
    c=c_.melt(var_name='column', value_name='value')
    d=d_.melt(var_name='column', value_name='value')
    e=e_.melt(var_name='column', value_name='value')
    repeating_index = np.tile(np.arange(168), int(np.ceil(483840 / 168)))[:483840]
    a['index'] = repeating_index
    b['index'] = repeating_index
    c['index'] = repeating_index
    d['index'] = repeating_index
    e['index'] = repeating_index
    return a,b,c,d,e

In [4]:
def date_(n):
    hours_per_day = 24
    hours_per_week=168
    days_per_month = 30
    hours_per_month = hours_per_day * days_per_month

    n['week'] = (n['index'] ) // hours_per_week + 1
#     n['day'] = ((n['index'] ) % hours_per_week) // hours_per_day  + 1
    n['month'] = np.abs(a1['index'] - 1) // hours_per_month + 1
    n['day_of_month'] = (np.abs(a1['index'] - 1) % hours_per_month) // hours_per_day + 1
#     n['day_of_week'] = (np.abs(a1['index'] - 1) % (hours_per_day * 7)) // hours_per_day + 1
    n['hour'] = n['index'] % 24
    n['day_of_week'] = np.abs(n['index'] // 24) % 7
    n['day'] = n['index'] // 24
    return n

<h1><b> Read Data

In [5]:
user_count=pd.read_csv('/kaggle/input/spatio-temporal-beam-level-traffic-forecasting/traffic_MR_number.csv')
thr_time=pd.read_csv('/kaggle/input/spatio-temporal-beam-level-traffic-forecasting/traffic_DLThpTime.csv')
ss=pd.read_csv('/kaggle/input/spatio-temporal-beam-level-traffic-forecasting/SampleSubmission.csv')
thr_vol=pd.read_csv('/kaggle/input/spatio-temporal-beam-level-traffic-forecasting/traffic_DLThpVol.csv') # test(target)
prb=pd.read_csv('/kaggle/input/spatio-temporal-beam-level-traffic-forecasting/traffic_DLPRB.csv')

In [6]:
''' in sample submission file there is 967680 rows for w5-w6 and w10-w11 prediction
    so when you divide 967680 by 2 weeks you will get 483840 per each week
    then divide it by 168 hours you will get 2880 
    ##################
    about rows and columns 
    we have 2880 cloumns and 840 rows.which means that we have 5 weaks,each week 
    has 168 hours 
'''

' in sample submission file there is 967680 rows for w5-w6 and w10-w11 prediction\n    so when you divide 967680 by 2 weeks you will get 483840 per each week\n    then divide it by 168 hours you will get 2880 \n    ##################\n    about rows and columns \n    we have 2880 cloumns and 840 rows.which means that we have 5 weaks,each week \n    has 168 hours \n'

In [7]:
user_count.drop('Unnamed: 0',axis=1,inplace=True)
thr_time.drop('Unnamed: 0',axis=1,inplace=True)
thr_vol.drop('Unnamed: 0',axis=1,inplace=True)
prb.drop('Unnamed: 0',axis=1,inplace=True)

In [8]:
a1,a2,a3,a4,a5=all_weeks(thr_time)
b1,b2,b3,b4,b5=all_weeks(thr_vol)
c1,c2,c3,c4,c5=all_weeks(user_count)
d1,d2,d3,d4,d5=all_weeks(prb)

In [9]:
a1,a2,a3,a4,a5=melt_(a1,a2,a3,a4,a5)
b1,b2,b3,b4,b5=melt_(b1,b2,b3,b4,b5)
c1,c2,c3,c4,c5=melt_(c1,c2,c3,c4,c5)
d1,d2,d3,d4,d5=melt_(d1,d2,d3,d4,d5)

In [10]:
a1=date_(a1)
a2=date_(a2)
a3=date_(a3)
a4=date_(a4)
a5=date_(a5)

In [11]:
b1=date_(b1)
b2=date_(b2)
b3=date_(b3)
b4=date_(b4)
b5=date_(b5)

In [12]:
c1=date_(c1)
c2=date_(c2)
c3=date_(c3)
c4=date_(c4)
c5=date_(c5)

In [13]:
d1=date_(d1)
d2=date_(d2)
d3=date_(d3)
d4=date_(d4)
d5=date_(d5)

In [14]:
# ss.tail()

In [15]:
a1['ID']='traffic_DLThpVol_test_5w-6w_'+a1['index'].astype('str')+'_'+a1['column']
a2['ID']='traffic_DLThpVol_test_6w-7w_'+a2['index'].astype('str')+'_'+a2['column']
a3['ID']='traffic_DLThpVol_test_7w-8w_'+a3['index'].astype('str')+'_'+a3['column']
a4['ID']='traffic_DLThpVol_test_8w-9w_'+a4['index'].astype('str')+'_'+a4['column']
a5['ID']='traffic_DLThpVol_test_10w-11w_'+a5['index'].astype('str')+'_'+a5['column']

In [16]:
b1['ID']='traffic_DLThpVol_test_5w-6w_'+b1['index'].astype('str')+'_'+b1['column']
b2['ID']='traffic_DLThpVol_test_6w-7w_'+b2['index'].astype('str')+'_'+b2['column']
b3['ID']='traffic_DLThpVol_test_7w-8w_'+b3['index'].astype('str')+'_'+b3['column']
b4['ID']='traffic_DLThpVol_test_8w-9w_'+b4['index'].astype('str')+'_'+b4['column']
b5['ID']='traffic_DLThpVol_test_10w-11w_'+b5['index'].astype('str')+'_'+b5['column']

In [17]:
c1['ID']='traffic_DLThpVol_train_0w-1w_'+c1['index'].astype('str')+'_'+c1['column']
c2['ID']='traffic_DLThpVol_train_1w-2w_'+c2['index'].astype('str')+'_'+c2['column']
c3['ID']='traffic_DLThpVol_train_2w-3w_'+c3['index'].astype('str')+'_'+c3['column']
c4['ID']='traffic_DLThpVol_train_3w-4w_'+c4['index'].astype('str')+'_'+c4['column']
c5['ID']='traffic_DLThpVol_train_4w-5w_'+c5['index'].astype('str')+'_'+c5['column']

In [18]:
d1['ID']='traffic_DLThpVol_train_0w-1w_'+d1['index'].astype('str')+'_'+d1['column']
d2['ID']='traffic_DLThpVol_train_1w-2w_'+d2['index'].astype('str')+'_'+d2['column']
d3['ID']='traffic_DLThpVol_train_2w-3w_'+d3['index'].astype('str')+'_'+d3['column']
d4['ID']='traffic_DLThpVol_train_3w-4w_'+d4['index'].astype('str')+'_'+d4['column']
d5['ID']='traffic_DLThpVol_train_4w-5w_'+d5['index'].astype('str')+'_'+d5['column']

In [19]:
c2['week']=c2['week'].replace([1],[2])
c2['day_of_month']=c2['day_of_month'].replace([0,1, 2, 3, 4, 5, 6],[7,8,9,10,11,12,13])
c3['week']=c3['week'].replace([1],[3])
c3['day_of_month']=c3['day_of_month'].replace([0,1, 2, 3, 4, 5, 6],[14,15,16,17,18,19,20])
c4['week']=c4['week'].replace([1],[4])
c4['day_of_month']=c4['day_of_month'].replace([0,1, 2, 3, 4, 5, 6],[21,22,23,24,25,26,27])
c5['week']=c5['week'].replace([1],[5])
c5['month']=c5['month'].replace([1],[2])
d2['week']=d2['week'].replace([1],[2])
d2['day_of_month']=d2['day_of_month'].replace([0,1, 2, 3, 4, 5, 6],[7,8,9,10,11,12,13])
d3['week']=d3['week'].replace([1],[3])
d3['day_of_month']=d3['day_of_month'].replace([0,1, 2, 3, 4, 5, 6],[14,15,16,17,18,19,20])
d4['week']=d4['week'].replace([1],[4])
d4['day_of_month']=d4['day_of_month'].replace([0,1, 2, 3, 4, 5, 6],[21,22,23,24,25,26,27])
d5['week']=d5['week'].replace([1],[5])
d5['month']=d5['month'].replace([1],[2])

In [20]:
a1['week']=a1['week'].replace([1],[6])
a1['day_of_month']=a1['day_of_month'].replace([0,1, 2, 3, 4, 5, 6],[7,8,9,10,11,12,13])
a1['month']=a1['month'].replace([1],[2])
a2['week']=a2['week'].replace([1],[7])
a2['day_of_month']=a3['day_of_month'].replace([0,1, 2, 3, 4, 5, 6],[14,15,16,17,18,19,20])
a2['month']=a3['month'].replace([1],[2])
a3['week']=a3['week'].replace([1],[8])
a3['day_of_month']=a3['day_of_month'].replace([0,1, 2, 3, 4, 5, 6],[21,22,23,24,25,26,27])
a3['month']=a3['month'].replace([1],[2])
a4['week']=a4['week'].replace([1],[9])
a4['month']=a4['month'].replace([1],[3])
a5['week']=a5['week'].replace([1],[10])
a5['day_of_month']=a5['day_of_month'].replace([0,1, 2, 3, 4, 5, 6],[7,8,9,10,11,12,13])
a5['month']=a5['month'].replace([1],[3])
#
b1['week']=b1['week'].replace([1],[6])
b1['day_of_month']=b1['day_of_month'].replace([0,1, 2, 3, 4, 5, 6],[7,8,9,10,11,12,13])
b1['month']=b1['month'].replace([1],[2])
b2['week']=b2['week'].replace([1],[7])
b2['day_of_month']=b3['day_of_month'].replace([0,1, 2, 3, 4, 5, 6],[14,15,16,17,18,19,20])
b2['month']=b3['month'].replace([1],[2])
b3['week']=b3['week'].replace([1],[8])
b3['day_of_month']=b3['day_of_month'].replace([0,1, 2, 3, 4, 5, 6],[21,22,23,24,25,26,27])
b3['month']=b3['month'].replace([1],[2])
b4['week']=b4['week'].replace([1],[9])
b4['month']=b4['month'].replace([1],[3])
b5['week']=b5['week'].replace([1],[10])
b5['day_of_month']=b5['day_of_month'].replace([0,1, 2, 3, 4, 5, 6],[7,8,9,10,11,12,13])
b5['month']=b5['month'].replace([1],[3])

In [21]:
tr1=pd.concat([c1,c2,c3,c4,c5],axis=0)
tr2=pd.concat([d1,d2,d3,d4,d5],axis=0)
ts1=pd.concat([a1,a2,a3,a4,a5],axis=0)
ts2=pd.concat([b1,b2,b3,b4,b5],axis=0)

In [22]:
tr1['value_2']=tr2['value']

In [23]:
ts1['value_1']=ts2['value']

In [24]:
train=tr1
test=ts1

In [25]:
test.head()

,column,value,index,week,month,day_of_month,hour,day_of_week,day,ID,value_1
0,0_0_0,0.000000,0,6,2,8,0,0,0,traffic_DLThpVol_test_5w-6w_0_0_0_0,0.000000
1,0_0_0,0.000000,1,6,2,8,1,0,0,traffic_DLThpVol_test_5w-6w_1_0_0_0,0.000000
2,0_0_0,0.014916,2,6,2,8,2,0,0,traffic_DLThpVol_test_5w-6w_2_0_0_0,0.000000
3,0_0_0,0.000000,3,6,2,8,3,0,0,traffic_DLThpVol_test_5w-6w_3_0_0_0,0.000000
4,0_0_0,0.000000,4,6,2,8,4,0,0,traffic_DLThpVol_test_5w-6w_4_0_0_0,0.445035

In [26]:
train.sort_values(['index','week','day','month','day_of_month','day_of_week'], ignore_index=True, inplace=True)
test.sort_values(['index','week','day','month','day_of_month','day_of_week'], ignore_index=True, inplace=True)

In [27]:
train.head()

,column,value,index,week,month,day_of_month,hour,day_of_week,day,ID,value_2
0,0_0_0,0.000000,0,1,1,1,0,0,0,traffic_DLThpVol_train_0w-1w_0_0_0_0,0.066698
1,0_0_1,0.000000,0,1,1,1,0,0,0,traffic_DLThpVol_train_0w-1w_0_0_0_1,0.085882
2,0_0_2,0.000000,0,1,1,1,0,0,0,traffic_DLThpVol_train_0w-1w_0_0_0_2,0.000000
3,0_0_3,0.027642,0,1,1,1,0,0,0,traffic_DLThpVol_train_0w-1w_0_0_0_3,0.090813
4,0_0_4,0.055997,0,1,1,1,0,0,0,traffic_DLThpVol_train_0w-1w_0_0_0_4,0.214019

In [28]:
test.head()

,column,value,index,week,month,day_of_month,hour,day_of_week,day,ID,value_1
0,0_0_0,0.000000,0,6,2,8,0,0,0,traffic_DLThpVol_test_5w-6w_0_0_0_0,0.000
1,0_0_1,0.040340,0,6,2,8,0,0,0,traffic_DLThpVol_test_5w-6w_0_0_0_1,0.000
2,0_0_2,0.006534,0,6,2,8,0,0,0,traffic_DLThpVol_test_5w-6w_0_0_0_2,0.000
3,0_0_3,0.000000,0,6,2,8,0,0,0,traffic_DLThpVol_test_5w-6w_0_0_0_3,0.000
4,0_0_4,0.323395,0,6,2,8,0,0,0,traffic_DLThpVol_test_5w-6w_0_0_0_4,0.031

In [29]:
train['Lag']=test['value_1'].shift(-1)
train['Lag_1']=test['value'].shift(-1)
test['value_2']=train['value_2'].shift(1)
test['Lag_1']=train['value'].shift(1)

In [30]:
train=train.fillna(method='ffill')
test=test.fillna(method='bfill')

/tmp/ipykernel_33/1357076515.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  train=train.fillna(method='ffill')
/tmp/ipykernel_33/1357076515.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  test=test.fillna(method='bfill')

In [31]:
# test.isna().sum()

In [32]:
Id=test['ID']

In [33]:
# test[483839:483842]

In [34]:
train.drop(['ID','column'],axis=1,inplace=True)
test.drop(['ID','column','value_1'],axis=1,inplace=True)

In [35]:
train.head()

,value,index,week,month,day_of_month,hour,day_of_week,day,value_2,Lag,Lag_1
0,0.000000,0,1,1,1,0,0,0,0.066698,0.000,0.040340
1,0.000000,0,1,1,1,0,0,0,0.085882,0.000,0.006534
2,0.000000,0,1,1,1,0,0,0,0.000000,0.000,0.000000
3,0.027642,0,1,1,1,0,0,0,0.090813,0.031,0.323395
4,0.055997,0,1,1,1,0,0,0,0.214019,0.000,0.160007

In [36]:
test.head()

,value,index,week,month,day_of_month,hour,day_of_week,day,value_2,Lag_1
0,0.000000,0,6,2,8,0,0,0,0.066698,0.000000
1,0.040340,0,6,2,8,0,0,0,0.066698,0.000000
2,0.006534,0,6,2,8,0,0,0,0.085882,0.000000
3,0.000000,0,6,2,8,0,0,0,0.000000,0.000000
4,0.323395,0,6,2,8,0,0,0,0.090813,0.027642

In [37]:
# X=train.drop('Lag',axis=1)
# y=train['Lag'].copy()
# X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=10)

In [38]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import SGDRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import BaggingRegressor
from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor

In [39]:
# xg= XGBRegressor()
# xg.fit(X_train,y_train)
# y_pred=xg.predict(X_test)
# mean_absolute_error(y_pred,y_test)

In [40]:
# from sklearn.ensemble import VotingRegressor
# xg = VotingRegressor([
#     ('cb',CatBoostRegressor() ),
#     ('lgb',LGBMRegressor()),
#     ('xgb', XGBRegressor()),
# ])

In [41]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import SGDRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import BaggingRegressor
from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.model_selection import TimeSeriesSplit
X=train.drop("Lag",axis=1).values
y=train["Lag"].values
scores=[]
kf=TimeSeriesSplit(n_splits=5)
for train_index,test_index in kf.split(X,y):
    X_train,y_train=X[train_index],y[train_index]
    X_test,y_test=X[test_index],y[test_index]

    xg= LGBMRegressor(random_state=42)
    xg.fit(X_train,y_train)
    y_pred=xg.predict(X_test)
    scores.append(mean_absolute_error(y_pred,y_test))

print("mean:",np.mean(scores))

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.073804 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 839
[LightGBM] [Info] Number of data points in the train set: 403200, number of used features: 10
[LightGBM] [Info] Start training from score 0.295015
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.268077 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 873
[LightGBM] [Info] Number of data points in the train set: 806400, number of used features: 10
[LightGBM] [Info] Start training from score 0.298343
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.362597 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 907
[LightGBM] [Info] Number of data points in the train set: 1209600, number of used features: 10
[LightGBM] [Info] Start training from score 0.313295
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.457755 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 941
[LightGBM] [Info] Number of data points in the train set: 1612800, number of used features: 10
[LightGBM] [Info] Start training from score 0.317575
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.653420 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 975
[LightGBM] [Info] Number of data points in the train set: 2016000, number of used features: 10
[LightGBM] [Info] Start training from score 0.319881
mean: 0.20064962895347788

In [43]:
xg.fit(X,y)
test['targrt']=xg.predict(test)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.872241 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1006
[LightGBM] [Info] Number of data points in the train set: 2419200, number of used features: 10
[LightGBM] [Info] Start training from score 0.321169

In [44]:
submission=pd.DataFrame({"ID":Id,"Target":test['targrt']})
submission.to_csv("traffic_5.csv",index=False)

In [45]:
submission.head()

                                    ID    Target
0  traffic_DLThpVol_test_5w-6w_0_0_0_0  0.064978
1  traffic_DLThpVol_test_5w-6w_0_0_0_1  0.064978
2  traffic_DLThpVol_test_5w-6w_0_0_0_2  0.064978
3  traffic_DLThpVol_test_5w-6w_0_0_0_3  0.064791
4  traffic_DLThpVol_test_5w-6w_0_0_0_4  0.079447